language: php
php:
    - 5.5
    - 5.6
    - 7.0
before_script: 
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install
script:
    - php vendor/bin/phpunit -c vendor/playground/faq
    - php vendor/bin/phpunit -c vendor/playground/user
    - php vendor/bin/phpunit -c vendor/playground/facebook
    - php vendor/bin/phpunit -c vendor/playground/cms
    - php vendor/bin/phpunit -c vendor/playground/core
    - php vendor/bin/phpunit -c vendor/playground/design
    - php vendor/bin/phpunit -c vendor/playground/flow
    - php vendor/bin/phpunit -c vendor/playground/partnership
    - php vendor/bin/phpunit -c vendor/playground/reward
    - php vendor/bin/phpunit -c vendor/playground/game
    - php vendor/bin/phpunit -c vendor/playground/stats
    - php vendor/bin/phpunit -c vendor/playground/translate
after_script:
    - php vendor/bin/coveralls
notifications:
    email:
        on_success: always
        on_failure: always
