<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>

<div id="sidebar-homepage" class="sidebar span4">
	<!-- BLOCK TONNES CADEAUX -->
    <div class="tonnes-cadeaux sd-block">
    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-gifts.png')?>" width="84" height="82" border="0" alt="gifts" />
		<p class="green"><?php echo $this->translate('Win a lot of gits !'); ?></p>
    	<div class="txt"><?php echo $this->translate('Sign up and join the Playground contests our partners to win loads of gifts.'); ?></div>
    	<div class="accroche"><?php echo $this->translate('Playground is 100% free!'); ?></div>
    	<div class="btn btn-success"><a href="#"><?php echo $this->translate('Sign up now!'); ?></a></div>
    	<div class="btn btn-inverse"><a href="#"><?php echo $this->translate('Connection'); ?></a></div>
    </div><!-- END BLOCK TONNES CADEAUX -->

    <!-- ADSERVING SIDEBAR -->
    <!--
    <div id="ad-sidebar" class="sidebar-block">
    	<img src="<?php //echo $this->frontendAssetPath('images/adserving/adserving-sidebar.jpg')?>" border="0" />
    </div>
    -->
    <!-- END ADSERVING SIDEBAR -->

    <?php if($this->facebookUrl()): ?>
    <!-- BLOCK FACEBOOK -->
    <div class="fb-box sd-block">
    	<p class="green"><?php echo $this->translate('Join us on Facebook'); ?><?php echo $this->translate('Join us on Facebook'); ?></p>
    	<div class="fb-like-box" data-href="<?php echo $this->facebookUrl(); ?>" data-width="225" data-height="250" data-show-faces="true" data-stream="false" data-border-color="#eeefef" data-header="false"></div>
    </div><!-- END BLOCK FACEBOOK -->
    <?php endif; ?>

    <!-- BLOCK NEWSLETTER -->
    <div class="sd-block newsletter">
    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-newsletter.png')?>" width="82" height="81" border="0" alt="newsletter" />
		<p class="green"><?php echo $this->translate('Sign up for the newsletter and never miss a game!'); ?></p>
    	<?php if(!$this->zfcUserIdentity()): ?>
	    	<form action="" method="POST">
	    		<input class="input" type="email" name="email" value="<?php echo $this->translate('Your email address'); ?>" onclick="if(this.value=='<?php echo $this->translate('Your email address'); ?>'){this.value=''}" onblur="if(this.value==''){this.value='<?php echo $this->translate('Your email address'); ?>'} " />
	    		<input class="btn btn-greendark" type="submit" value="Ok"/>
	    	</form>
	    <?php else: ?>
	    	<div class="btn btn-success"><a href="newsletter.php"><?php echo $this->translate('Sign up now!'); ?></a></div>
	    <?php endif; ?>
    </div><!-- END BLOCK NEWSLETTER -->

    <!-- BLOCK HOW IT WORKS -->
    <div class="sd-block how-works">
    	<img src="<?php echo $this->frontendAssetPath('images/common/icon-question.png')?>" width="82" height="80" border="0" alt="question" />
		<p class="green"><?php echo $this->translate('How it works ?'); ?></p>
    	<ul class="links-list">
    		<li class="connect"><a href="#"><?php echo $this->translate('Register or log in to your account'); ?></a></li>
    		<li class="game-play"><a href="#"><?php echo $this->translate('Participate in contests to win prizes'); ?></a></li>
    		<li class="gain-points"><a href="#"><?php echo $this->translate('Collect points and earn badges.'); ?></a></li>
    	</ul>
    	<div class="link">&gt; <a href="#" class="green"><?php echo $this->translate('See how to earn more points!'); ?></a></div>
    </div><!-- END BLOCK HOW IT WORKS -->

</div>