<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php $title = $this->isCreate ? $this->translate('Create Appli') : $this->translate('Edit Appli'); echo $title; ?></h1>

<strong><?php echo $this->translate('Your Facebook app must have its "Require App Secret" set to false (go in settings / advanced on the security tab and disable "Require App Secret")') ?></strong><br/><br/>

<p><?php echo $this->translate("to create a tab app on a page, you'll have to call this URL with the appId and the url of your game as parameters:")?> <a href="https://www.facebook.com/dialog/pagetab?app_id=111111111111111&redirect_uri=https://www.mycompany.com/quiz/myquiz">https://www.facebook.com/dialog/pagetab?app_id=111111111111111&redirect_uri=https://www.mycompany.com/quiz/myquiz</a></p>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div class="facebook-admin">
    <?php echo $this->formHidden($form->get('id')); ?>

    <div class="label-input">
        <?php echo $this->formLabel($form->get('appId')); ?>
        <?php echo $this->formInput($form->get('appId')); ?>
        <?php echo $this->formElementErrors($form->get('appId')) ?>
    </div>
<?php if ($this->isCreate && sizeof($form->get('appIdRetrieved')->getValueOptions())): ?>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('appIdRetrieved')); ?>
        <?php echo $this->formSelect($form->get('appIdRetrieved')); ?>
        <?php echo $this->formElementErrors($form->get('appIdRetrieved')) ?>
    </div>
<?php else: ?>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('appName')); ?>
        <?php echo $this->formInput($form->get('appName')); ?>
        <?php echo $this->formElementErrors($form->get('appName')) ?>
    </div>
<?php endif; ?>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('appSecret')); ?>
        <?php echo $this->formInput($form->get('appSecret')); ?>
        <?php echo $this->formElementErrors($form->get('appSecret')) ?>
	</div>
	<div class="label-input">
        <?php echo $this->formLabel($form->get('pages')); ?>
        <?php echo $this->formMultiCheckbox($form->get('pages')); ?>
        <?php echo $this->formElementErrors($form->get('pages')) ?>
	</div>
</div>

<?php echo $this->form()->closeTag() ?>

<script>
$("#appIdRetrieved").change(function() {
    window.open('https://developers.facebook.com/apps/'+$("select option:selected").val(),'_blank','',false)
  //open window https://developers.facebook.com/apps/414761728645581
});
</script>
