<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php echo $this->translate('Create role'); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate'));?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content">
    <?php echo $this->formHidden($form->get('id')); ?>

    <div class="label-input">
        <?php echo $this->formLabel($form->get('roleId')); ?>
        <?php echo $this->formInput($form->get('roleId')); ?>
        <?php echo $this->formElementErrors($form->get('roleId')) ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('parentRoleId')); ?>
        <?php echo $this->formSelect($form->get('parentRoleId')); ?>
        <?php echo $this->formElementErrors($form->get('parentRoleId')) ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
