<?php
$children = $this->viewModel()
->getCurrent()
->getChildren();
if(isset($children[0])){
    $ourView  = $children[0];
}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Playground')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Scripts -->
    <?php /*echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))*/

    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->frontendAssetPath('/images/favicon.ico')))?>
    <?php echo $this->plugin('HeadScript'); ?>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
</head>

<body>

    <div class="userbar">
        <div class="inner">
            <div class="left">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a href="<?php echo $this->url('admin') ?>">
                    <img src="<?php echo $this->adminAssetPath('images/logo.svg'); ?>" alt="Administration" border="0" width="120" />
                </a>
            </div>
            <div class="right">
                <div><span class="user"><?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?></span>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo $this->url('admin/logout', array('channel' => $this->channel)) ?>" class="logout">Se déconnecter</a></div>
                <div class="btn-website"><a href="<?php echo $this->url('frontend', array('channel' => $this->channel)) ?>" class="home" target="_blank">Accéder au site</a></div>
            </div>
        </div>
    </div>
    <!-- <div class="navbar navbar-fixed-top"> -->
    <div class="navbar">
        <ul class='nav'>
            <?php echo $this->adminMenu()->setPartial(array('playground-design/common/menu.phtml', 'default'));
            ?>
        </ul>
    </div>

    <div class="container">
        <?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
        <ul class="flashMessages">
            <?php foreach ($ourView->flashMessages as $fMessage) : ?>
            <li><?php echo $fMessage; ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <?php echo $this->content; ?>

        <footer>
            <p>V2.0.1 Dazzler - &copy; 2015 by Grégory Besson. All rights reserved.</p>
        </footer>
    </div>
    <!-- /container -->
    <?php echo $this->plugin('InlineScript'); ?>
</body>
</html>