<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $downloadLink = $this->url('admin/'. $this->game->getClassType() .'/download', array('gameId' => $this->game->getId()));?>

<h1><a href="<?php echo $this->url('admin/playgroundgame/edit-postvote', array('gameId' => $this->gameId)) ?>"><?php echo $this->game->getTitle(); ?></a></h1>

<h3><?php echo $this->translate('Liste des Participants'); ?></h3>

<a href='<?php echo $downloadLink ?>'>Export CSV</a>
<table class="table">
    <tr>
        <?php foreach ($this->header as $k => $v): ?>
            <th><?php echo $k; ?></th>
        <?php endforeach; ?>

        <th><?php echo $this->translate('Moderate'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->entries as $entry): ?>
        <tr>
            <?php foreach ($entry as $key => $value):?>
                <td>
                    <?php 
                    if(substr($value, -4) == '.png' || substr($value, -4) == '.jpg' || substr($value, -4) == '.gif'){
                        echo "<img src='/". $value ."' width='40'><br/>";
                    } elseif(substr($value, -4) == '.mp4'){
                        echo "<video src='". $value ."' width='80' controls='true'><br/>";
                    } else{
                        echo $value;
                    }
                    ?>
            </td>
            <?php endforeach; ?>

            <?php $editLink = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $entry['id']));?>
            <td><a href='<?php echo $editLink ?>'><?php echo $this->translate('Moderate'); ?></a></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php echo (count($this->paginator)>1)?$this->paginationControl($this->paginator, 'Sliding', 'playground-game/game/pagination_entrylist', array('classType' => $this->game->getClassType()  ,'gameId' => $this->gameId)):''; ?>