<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $validation = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $post->getId(), 'status' => 'validation'));?>
<?php $rejection = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $post->getId(), 'status' => 'rejection'));?>

<h2 class="green"><?php echo $this->translate('Aperçu du post')?></h2>
<div>
    <a href='<?php echo $rejection ?>'><?php echo $this->translate('Reject'); ?></a>
    <a href='<?php echo $validation ?>'><?php echo $this->translate('Validate'); ?></a>
</div>

<div class="row-fluid">
   	<?php foreach($this->post->getPostElements() as $e):?>
	<?php echo "<h3>".$e->getName()."</h3>";?>
	<?php 
		$val = $e->getValue();
		if(substr($val, -4) == '.png' || substr($val, -4) == '.jpg' || substr($val, -4) == '.gif'){
			echo "<img src='/". $val ."' width='40'><br/>";
		} elseif(substr($val, -4) == '.mp4'){
			echo "<video src='". $val ."' width='320' controls='true'><br/>";
		} else{
			echo $val;
		}
	?>
	<br/>
	<?php endforeach;?>
</div>
<div>
    <a href='<?php echo $rejection ?>'><?php echo $this->translate('Reject'); ?></a>
    <a href='<?php echo $validation ?>'><?php echo $this->translate('Validate'); ?></a>
</div>