<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounddesign');// Pour le texte ?>

<?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
$this->headMeta()->setCharset('UTF-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable = no');
?>
<?php echo $this->headMeta(); ?>


<?php // Don't forget to place the MS favicon.ico in the root directory as it looks for it by default. ?>
<?php echo $this->headLink(array('rel' => 'apple-touch-icon', 'href' => '/favicon.png'))?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.png'))?>
<?php echo $this->plugin('HeadStyle'); ?>
<?php echo $this->plugin('HeadScript'); ?>